spring:
  application:
    name: springb_fskill

open:
  api:
    title: API document
    version: v1.0.0
    description: API Service Description
    serverUrl: http://localhost:8080
    serverName: server test