server:
  port: 8080
spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
      #    Giá trị	                         Mô tả
      #     none                Không tự động tạo / cập nhật schema (cần tạo schema thủ công).
      #    update	              Cập nhật schema nhưng không xóa dữ liệu.
      #    create               Tạo lại toàn bộ schema mỗi lần chạy (xóa sạch dữ liệu cũ).
      #  create-drop	          Tạo schema khi app chạy & xóa khi app dừng.
      #   validate	            Kiểm tra schema, nhưng không tự động sửa.
open:
  api:
    title: API document
    version: v1.0.0
    description: API Service Description
    serverUrl: http://localhost:${server.port}
    serverName: server dev